task done in TypeScript
YuliaLabutkina/test pull request #1
Opened 2021-02-09 23:06 UTC by YuliaLabutkina

2021-02-10 09:57 UTC, max-mykhailenko requested changes

2021-02-10 09:57 UTC, max-mykhailenko commented on 0.3.0
> +
Зачем этот файл?

2021-02-10 09:57 UTC, max-mykhailenko commented on package.json
> +    "eslint-plugin-simple-import-sort": "^7.0.0",
Все зависимости должны быть exact. Для этого необходимо создать файл npmrc с правилом exact, либо каждый раз при установке пакета дописывать --exact

2021-02-10 09:57 UTC, max-mykhailenko commented on src/components/Button/Button.tsx
> +  type?: string;
type это не строчный тип, так как у него всего пара возможных значений

2021-02-10 09:57 UTC, max-mykhailenko commented on src/components/Table/Table.tsx
> +  const deleteRow = (id: number): void => {
Парой строк выше id это строка, лучше свести идентификаторы к одному типу, если это возможно

2021-02-10 09:57 UTC, max-mykhailenko commented on src/components/Table/Table.tsx
> +            table.map((tableRow: IObject[], index: number) => (
Типизация аргументов этой функции это избыточное занятие, тип `tableRow` должен выводится автоматически исходя из типа table

2021-02-10 09:57 UTC, max-mykhailenko commented on src/components/Table/Table.tsx
> +                {tableRow.map(({ id, number }: IObject, idRow: number) => (
Типизация аргументов этой функции это избыточное занятие, тип id, number  должен выводится автоматически исходя из типа tableRow

2021-02-10 09:57 UTC, max-mykhailenko commented on src/components/Table/Table.tsx
> +                        ({ indexNumber }: INearestAmount) => indexNumber === id,
indexNumber тип должен вывестись автоматически потому что у тебя затипизирован comingNumbers

2021-02-10 09:57 UTC, max-mykhailenko commented on src/components/Table/Table.tsx
> +                            indexPercent: number,
Все типы здесь избыточны по причинам описанным выше

2021-02-10 09:57 UTC, max-mykhailenko commented on src/components/Table/Table.tsx
> +            {average.map(({ id, average }: IAverageArray) => (
избыточная типизация

2021-02-10 09:57 UTC, max-mykhailenko commented on src/components/TableCreation/TableCreation.tsx
> +  const dispatch: AppDispatch = useDispatch();
Здесь у тебя должен сработать тип, который возвращает функция useDispatch без необходимости вручную его указывать

2021-02-10 09:57 UTC, max-mykhailenko commented on src/components/TableCreation/TableCreation.tsx
> +    const table: Array<IObject[]> = createTable(row, column);
`: Array<IObject[]>` избыточный тип, так как функция createTable должна возвращать типизированные данные

2021-02-10 09:57 UTC, max-mykhailenko commented on src/interface/interface.ts
> +export interface IObject {
Object самое непонятное название типа ever, рекомендую что-то типа ICell

2021-02-10 09:57 UTC, max-mykhailenko commented on src/js/calculateAverage.ts
> +  for (let i = row; i > 0; i = i - 1) {
О, заодно перепиши этот for на reduce, map или любой другой околофункциональный метод. Тебе могут помочь методы вида Array.from({length: X}) и тд

2021-02-10 09:57 UTC, max-mykhailenko commented on src/js/calculateAverage.ts
> +  for (let i = column; i > 0; i = i - 1) {
О, заодно перепиши этот for на reduce, map или любой другой околофункциональный метод. Тебе могут помочь методы вида Array.from({length: X}) и тд

2021-02-10 09:57 UTC, max-mykhailenko commented on src/js/calculateAverage.ts
> +    const average: number = createAverage(columns, table, row);
: number лишняя типизация

2021-02-10 09:57 UTC, max-mykhailenko commented on src/js/calculateAverage.ts
> +  let columns: number = column;
: number лишняя типизация

2021-02-10 09:57 UTC, max-mykhailenko commented on tsconfig.json
> +    "target": "es5",
Ну это очень древняя цель, можно повыше поставить

2021-02-11 09:09 UTC, YuliaLabutkina commented on src/components/Table/Table.tsx
> +  const deleteRow = (id: number): void => {
Я рандомно создаю id для чисел с помощью пакета uuid и это string. А для удаления строки таблицы мне нужен id масива который нужно удалить и это number. По этому типы разные. Можно оставить так?

2021-02-11 09:12 UTC, YuliaLabutkina commented on package.json
> +    "eslint-plugin-simple-import-sort": "^7.0.0",
Я добавила файл .npmrc и прописала  в нем  save-exact=true. Я верно седелала?

2021-02-11 12:44 UTC, max-mykhailenko requested changes

2021-02-11 12:44 UTC, max-mykhailenko commented on package.json
> +    "typescript": "^4.1.3",
зависимость не точная, как и многие другие

2021-02-11 12:44 UTC, max-mykhailenko commented on package.json
> +    "eslint-plugin-simple-import-sort": "^7.0.0",
Да, но нужно править все уже прописанные зависимости

2021-02-11 12:44 UTC, max-mykhailenko commented on src/components/Table/Table.tsx
> +  const deleteRow = (id: number): void => {
То есть это не id, а итерация?

2021-02-11 12:44 UTC, max-mykhailenko commented on src/js/calculateAverage.ts
> +  Array.from({ length: column }, () => {
Вот как раз array.from отдает новый массив, который нужно и было присвоить в averageArray после последующих манипуляций через reduce или map, бо в текущем случае это то еще извращение

2021-02-11 12:44 UTC, max-mykhailenko commented on src/js/calculationsNearestAmounts.ts
> +  const arrayAmount: ICell[] = table.flat();
Лишняя типизация?

2021-02-11 12:44 UTC, max-mykhailenko commented on src/js/calculationsNearestAmounts.ts
> +  const difference: number[] = arrayAmount.map(({ number }) =>
Лишняя типизация?

2021-02-11 12:44 UTC, max-mykhailenko commented on src/js/calculationsNearestAmounts.ts
> +  mySet.forEach((number: number) =>
mySet.forEach попробуй заменить на reduce или map так, чтобы сразу сформировать переменную indexArray

2021-02-11 12:44 UTC, max-mykhailenko commented on src/js/calculationsNearestAmounts.ts
> +    (acc: INearestAmount[], el: ICell, id: number): INearestAmount[] => {
лишняя типизация

2021-02-11 12:44 UTC, max-mykhailenko commented on src/js/createTable.ts
> +  for (let i = row; i > 0; i -= 1) {
Замени for на что-то функциональное

2021-02-11 12:44 UTC, max-mykhailenko commented on src/js/createTable.ts
> +  for (let i = column; i > 0; i -= 1) {
Замени for на что-то функциональное

2021-02-11 12:44 UTC, max-mykhailenko commented on src/redux/selectors.ts
> +const getAverage = createSelector(
createSelector это скорее всего generic и типизируется как generic, убедись что все связано по типам

2021-02-11 12:44 UTC, max-mykhailenko commented on src/redux/table/table-action.ts
> +// const deleteIndexSelectedRow = createAction('table/DeleteIndexSelectedRow');
Закоментированный код можно удалить или дописать зачем нужен и когда расскоментировать

2021-02-11 12:44 UTC, max-mykhailenko commented on src/redux/table/table-reducer.ts
> +  return [...state.filter((row, index) => (index !== payload ? row : null))];
не совсем понимаю зачем spread оператор при условии что фильтр возвращает новый массив

2021-02-11 12:44 UTC, max-mykhailenko commented on src/redux/table/table-reducer.ts
> +    ...state.map(row =>
зачем это разбирать, если map и так возвращает новый массив?

2021-02-11 12:44 UTC, max-mykhailenko commented on tsconfig.json
> +    "target": "es5",
вопрос не решен

2021-02-14 17:19 UTC, YuliaLabutkina commented on tsconfig.json
> +    "target": "es5",
Какую лучше поставить?

2021-02-14 17:21 UTC, YuliaLabutkina commented on src/components/Table/Table.tsx
> +  const deleteRow = (id: number): void => {
Здесь передаю позицию(индекс) строки которую хочу удалить.

2021-02-14 18:02 UTC, YuliaLabutkina commented on src/redux/selectors.ts
> +const getAverage = createSelector(
Не совсем поняла этот момент. Подскажи пожалуйста как я должна убедиться что все связано по типам?

2021-02-16 13:11 UTC, max-mykhailenko approved these changes

2021-02-16 18:52 UTC, merged